name: youtube_asr

services:
  jupyter:
    volumes:
      - .:/root/youtube_asr
      - ${HF_CACHE_DIR:-/tmp/hf_cache}:/tmp/hf_cache
    build: .
    environment:
      HF_HOME: /tmp/hf_cache
    ports:
      - 127.0.0.1:${JUPYTER_PORT:-8888}:8888
      - 127.0.0.1:${TENSORBOARD:-6006}:6006
    entrypoint: /root/.venv/bin/python -m jupyter lab --port 8888 --allow-root --ip 0.0.0.0
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
